apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-db-lv
  name: ashu-db-lv
  namespace: ashu-project1
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector: # pod finder info 
    app: ashu-db
  type: ClusterIP
status:
  loadBalancer: {}
